/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiPublicIngestWeatherRouteImport } from './routes/api/public/ingest-weather'
import { Route as ApiPublicTilesLayerZXYRouteImport } from './routes/api/public/tiles/$layer/$z/$x/$y'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestWeatherRoute = ApiPublicIngestWeatherRouteImport.update({
  id: '/api/public/ingest-weather',
  path: '/api/public/ingest-weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTilesLayerZXYRoute = ApiPublicTilesLayerZXYRouteImport.update({
  id: '/api/public/tiles/$layer/$z/$x/$y',
  path: '/api/public/tiles/$layer/$z/$x/$y',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/ingest-weather': typeof ApiPublicIngestWeatherRoute
  '/api/public/tiles/$layer/$z/$x/$y': typeof ApiPublicTilesLayerZXYRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/ingest-weather': typeof ApiPublicIngestWeatherRoute
  '/api/public/tiles/$layer/$z/$x/$y': typeof ApiPublicTilesLayerZXYRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/ingest-weather': typeof ApiPublicIngestWeatherRoute
  '/api/public/tiles/$layer/$z/$x/$y': typeof ApiPublicTilesLayerZXYRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/public/ingest-weather'
    | '/api/public/tiles/$layer/$z/$x/$y'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/public/ingest-weather'
    | '/api/public/tiles/$layer/$z/$x/$y'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/public/ingest-weather'
    | '/api/public/tiles/$layer/$z/$x/$y'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiPublicIngestWeatherRoute: typeof ApiPublicIngestWeatherRoute
  ApiPublicTilesLayerZXYRoute: typeof ApiPublicTilesLayerZXYRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-weather': {
      id: '/api/public/ingest-weather'
      path: '/api/public/ingest-weather'
      fullPath: '/api/public/ingest-weather'
      preLoaderRoute: typeof ApiPublicIngestWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tiles/$layer/$z/$x/$y': {
      id: '/api/public/tiles/$layer/$z/$x/$y'
      path: '/api/public/tiles/$layer/$z/$x/$y'
      fullPath: '/api/public/tiles/$layer/$z/$x/$y'
      preLoaderRoute: typeof ApiPublicTilesLayerZXYRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiPublicIngestWeatherRoute: ApiPublicIngestWeatherRoute,
  ApiPublicTilesLayerZXYRoute: ApiPublicTilesLayerZXYRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
